name: Silaty

on:
 push:
  branches:
   - main

env:
  SOURCE_DIR: ${{ github.workspace }}

jobs:

# macOS ----------------------------------------------------------------
 silatymacos:
  name: macOS
  runs-on: macos-latest
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      version: 6.5.0
      host: mac
      target: desktop
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       mkdir release
       mv Silaty.app ./release
       cd release
       ../qt/Qt/6.5.0/macos/bin/macdeployqt ./Silaty.app
       ls ./
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "macos"
      path: ./release/Silaty.app

# windows ----------------------------------------------------------------
 silatywindows:
  name: Windows
  runs-on: windows-latest
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      arch: win64_mingw
      version: 6.5.0
      host: windows
      target: desktop
      tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       mkdir unzip_cqtd
       choco install wget --no-progress
       C:\msys64\usr\bin\wget.exe -O cqtd.exe https://github.com/QuasarApp/CQtDeployer/releases/download/v1.6.2285/CQtDeployer_1.6.2285.1507045_Windows_AMD64.exe
       ./cqtd.exe install --accept-messages --root D:\a\SilatyQt\SilatyQt\qt\Qt\ --confirm-command
       cd release
       ../qt/Qt/1.6/CQtDeployer.exe -bin Silaty.exe -binDir ../winBin -qmake ../qt/Qt/6.5.0/mingw_64/bin/qmake.exe qif -extraPlugin ../qt/Qt/6.5.0/mingw_64/plugins/multimedia -icon ../images/Icons/silaty.ico -description "A neat prayer reminder application" -deployVersion 1.6
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "windows"
      path: ./release/DistributionKit/InstallerSilaty.exe

# linux ----------------------------------------------------------------
 silatylinux:
  name: Linux
  runs-on: ubuntu-22.04
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      version: 6.5.0
      host: linux
      target: desktop
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       wget -O cqtd.deb https://github.com/QuasarApp/CQtDeployer/releases/download/v1.6.2285/CQtDeployer_1.6.2285.1507045_Linux_x86_64.deb
       sudo apt install ./cqtd.deb
       cqtdeployer -bin Silaty qif -extraPlugin ./qt/Qt/6.5.0/gcc_64/plugins/multimedia -icon ./images/Icons/silaty.png -description "A neat prayer reminder application" -deployVersion 1.6
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "linux"
      path: ./DistributionKit/InstallerSilaty.run
