name: Silaty

on:
 push:
  branches:
   - main

env:
  SOURCE_DIR:   ${{ github.workspace }}

jobs:

# linux ----------------------------------------------------------------
 jqtlinux:
  name: Linux
  runs-on: ubuntu-22.04
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      version: 6.5.0
      host: linux
      target: desktop
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==2.1.0'

   - name: Compile Silaty
     run: qmake && make -j8

   - name: test
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       ls
     
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "linux"
      path: ./Silaty
