name: Silaty

on:
 push:
  branches:
   - main

env:
  SOURCE_DIR:   ${{ github.workspace }}

jobs:

# windows ----------------------------------------------------------------
 silatywindows:
  name: Windows
  runs-on: windows-latest
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      arch: win64_mingw
      version: 6.5.0
      host: windows
      target: desktop
      tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       mkdir unzip_cqtd
       choco install wget --no-progress
       C:\msys64\usr\bin\wget.exe -O cqtd.zip https://github.com/QuasarApp/CQtDeployer/releases/download/v1.6.2285/CQtDeployer_1.6.2285.1507045_Windows_AMD64.zip
       7z x cqtd.zip -oqt\Qt\
       cd release
       ../qt/Qt/CQtDeployer.bat -bin Silaty.exe -qmake ../qt/Qt/6.5.0/mingw_64/bin/qmake.exe qif -extraPlugin ../qt/Qt/6.5.0/mingw_64/plugins/multimedia
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "windows"
      path: ./DistributionKit/InstallerSilaty.exe

# linux ----------------------------------------------------------------
 silatylinux:
  name: Linux
  runs-on: ubuntu-22.04
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      version: 6.5.0
      host: linux
      target: desktop
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==2.1.0'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       wget -O cqtd.deb https://github.com/QuasarApp/CQtDeployer/releases/download/v1.6.2285/CQtDeployer_1.6.2285.1507045_Linux_x86_64.deb
       sudo apt install ./cqtd.deb
       cqtdeployer -bin Silaty qif -extraPlugin ./qt/Qt/6.5.0/gcc_64/plugins/multimedia -icon ./images/Icons/silaty.png
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "linux"
      path: ./DistributionKit/InstallerSilaty.run
