name: Silaty

on:
 push:
  branches:
   - main

env:
  SOURCE_DIR:  ${{ github.workspace }}

jobs:

# windows ----------------------------------------------------------------
 silatywindows:
  name: Windows
  runs-on: windows-latest
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      arch: win64_mingw
      version: 6.5.1
      host: windows
      target: desktop
      tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     continue-on-error: true
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       cd release
       ../qt/Qt/6.5.1/mingw_64/bin/windeployqt.exe Silaty.exe

   - uses: sibiraj-s/action-eslint@v1
     with:
        extensions: 'js, jsx, ts, tsx'
        annotations: false
     env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
   - name: Release Silaty
     if: always()
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "windows"
      path: ./release/*

# linux ----------------------------------------------------------------
 silatylinux:
  name: Linux
  runs-on: ubuntu-22.04
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      version: 6.5.1
      host: linux
      target: desktop
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       wget -O cqtd.deb https://github.com/QuasarApp/CQtDeployer/releases/download/v1.6.2285/CQtDeployer_1.6.2285.1507045_Linux_x86_64.deb
       sudo apt install ./cqtd.deb
       cqtdeployer -bin Silaty qif -extraPlugin ./qt/Qt/6.5.1/gcc_64/plugins/multimedia -icon ./images/Icons/silaty.png -deployVersion 1.6
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "linux"
      path: ./DistributionKit/InstallerSilaty.run

# macos ----------------------------------------------------------------
 silatymacos:
  name: macOS
  runs-on: macos-latest
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      version: 6.5.1
      host: mac
      target: desktop
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       mkdir release
       mv Silaty.app ./release
       cd release
       ../qt/Qt/6.5.1/macos/bin/macdeployqt ./Silaty.app -dmg -verbose=1
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "macos"
      path: ./release/Silaty.dmg
