name: Build Silaty

on: 
  workflow_dispatch

env:
  SOURCE_DIR:  ${{ github.workspace }}

jobs:

# windows ----------------------------------------------------------------
 silatywindows:
  name: Windows
  runs-on: windows-latest
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      arch: win64_mingw
      version: 6.5.1
      host: windows
      target: desktop
      tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       choco install wget --no-progress
       C:\msys64\usr\bin\wget.exe -O cqtd.exe https://github.com/QuasarApp/CQtDeployer/releases/download/v1.6.2285/CQtDeployer_1.6.2285.1507045_Windows_AMD64.exe
       ./cqtd.exe install --accept-messages --root D:\a\SilatyQt\SilatyQt\qt\Qt\ --confirm-command
       cd release
       ../qt/Qt/1.6/CQtDeployer.exe -bin Silaty.exe -qmake ../qt/Qt/6.5.1/mingw_64/bin/qmake.exe qif -extraPlugin ../qt/Qt/6.5.1/mingw_64/plugins/multimedia -extraData ../winBin/* -icon ../images/Icons/silaty.ico -deployVersion 1.6
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "windows"
      path: ./release/DistributionKit/InstallerSilaty.exe

# linux ----------------------------------------------------------------
 silatylinux:
  name: Linux
  runs-on: ubuntu-22.04
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      version: 6.5.1
      host: linux
      target: desktop
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       wget -O cqtd.deb https://github.com/QuasarApp/CQtDeployer/releases/download/v1.6.2285/CQtDeployer_1.6.2285.1507045_Linux_x86_64.deb
       sudo apt install ./cqtd.deb
       cqtdeployer -bin Silaty qif -extraPlugin ./qt/Qt/6.5.1/gcc_64/plugins/multimedia -icon ./images/Icons/silaty.png -deployVersion 1.6
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "linux"
      path: ./DistributionKit/InstallerSilaty.run

# linux-appimage -------------------------------------------------------
 silatylinux-appimage:
  name: Linux (AppImage)
  runs-on: ubuntu-20.04
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      version: 6.5.1
      host: linux
      target: desktop
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Install dependencies
     run: |
       sudo apt-get update
       sudo apt-get install libgl1-mesa-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libzstd-dev libxcb-image0-dev libxcb-util0-dev libxcb-cursor-dev

   - name: Compile Silaty
     run: |
       qmake -config release && make -j1

   - name: Install LinuxDeploy
     run: |
       wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
       wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
       chmod +x linuxdeploy-x86_64.AppImage
       chmod +x linuxdeploy-plugin-qt-x86_64.AppImage

   - name: Create AppImage
     run: |
       export QML_SOURCES_PATHS="${{env.QML_DIR_NIX}}"
       export QMAKE=${{env.REPO_DIR}}/Qt/${{env.QT_VERSION}}/gcc_64/bin/${{env.QMAKE}}
       export PATH=${{env.REPO_DIR}}/Qt/${{env.QT_VERSION}}/gcc_64/libexec:$PATH
       ./linuxdeploy-x86_64.AppImage --appdir AppDir -e ${{env.UNIXNAME}} -i deploy/linux/${{env.UNIXNAME}}.png -d deploy/linux/${{env.UNIXNAME}}.desktop --plugin qt --output appimage
       rm linuxdeploy-x86_64.AppImage
       rm linuxdeploy-plugin-qt-x86_64.AppImage
       mv *.AppImage ${{env.EXECUTABLE}}-${{env.VERSION}}-Linux.AppImage

   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "linux (appimage)"
      path: ${{env.EXECUTABLE}}-${{env.VERSION}}-Linux.AppImage

# macos ----------------------------------------------------------------
 silatymacos:
  name: macOS
  runs-on: macos-latest
  steps:
   - name: Check Git repository
     uses: actions/checkout@v3
     with:
      submodules: recursive

   - name: Install Qt
     uses: jurplel/install-qt-action@v3.2.1
     with:
      version: 6.5.1
      host: mac
      target: desktop
      dir: '${{github.workspace}}/qt/'
      modules: 'qtmultimedia'
      aqtversion: '==3.1.6'

   - name: Compile Silaty
     run: qmake -config release && make -j1

   - name: Package Silaty
     working-directory: ${{ env.SOURCE_DIR }}
     run: |
       mkdir release
       mv Silaty.app ./release
       cd release
       ../qt/Qt/6.5.1/macos/bin/macdeployqt ./Silaty.app -dmg -verbose=1
       
   - name: Release Silaty
     uses: actions/upload-artifact@v2.2.4
     with:
      name: "macos"
      path: ./release/Silaty.dmg
